POST http://localhost:5000/student/register HTTP/1.1
Content-Type: application/json

{
    "email":"ff@gmail.com"
}

###
POST http://localhost:5000/student/login HTTP/1.1
Content-Type: application/json

{
    "email":"maheshkutty@gmail.com",
    "pass":"Mahesh@123"
}

###
POST http://localhost:5000/mentor/login HTTP/1.1
Content-Type: application/json

{
    "email":"h@gmail.com",
    "pass":"Mahesh@14"
}

###

GET  http://localhost:5000/doubts HTTP/1.1


###
GET http://localhost:5000/blogs HTTP/1.1

###
POST http://localhost:5000/student/request HTTP/1.1
Content-Type: application/json

{
  "sid":"8",
  "subjects":["maths"],
  "daysOfWeek":["monday"],
  "startTime":"11:00",
  "endTime":"12:00",
  "topics":["class 10 maths"]
}

###
POST http://localhost:5000/mentor/expertise HTTP/1.1
Content-Type: application/json

{
    "mid":5,
    "daysOfWeek":["sunday", "monday"],
    "subjects":["maths", "geography"],
    "startTime":"09:00",
    "endTime":"11:00"
}


###

POST http://localhost:5000/mentor/studentreq HTTP/1.1
Content-Type: application/json

{
    "mid":"5"
}

###
POST http://localhost:5000/student/showpendingmeet HTTP/1.1
Content-Type: application/json

{
    "sid":"8"
}

###
POST http://localhost:5000/student/showconfirmedmeet HTTP/1.1
Content-Type: application/json

{
    "sid":"8"
}

###
POST http://localhost:5000/mentor/accept-studentreq HTTP/1.1
Content-Type: application/json

{
    "rid":"4",
    "mid": "5",
    "sid": "8",
    "sdate": "29-01-2022"
}